### ISSUE TITLE
Unit Testing Job Templates page is not applicable anymore

### ISSUE THREAD

**Issue by mmdacheva** [cloudfoundry/docs-bosh#783] opened 2023-01-05 14:42 UTC
As of Ruby 3.2.0 the Kernel.taint function is not available anymore and therefore all tests start failing. The 'taint' function is used in the template.render call.

**Comment by rkoster** [comment] 2023-01-05 16:07
Could you provide steps to reproduce this issue? I could not find any references to `template.render` or `Kernel.taint`.

**Comment by mmdacheva** [comment] 2023-01-06 15:21
In this code block on line 14 there is a call of the render function for a variable named template: 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/59440238/211041620-721f289d-f0a6-46f7-9911-f457d319c858.png">

If you run this code you will receive the following error message:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/59440238/211042042-b4a18c8f-8c36-443e-b1c0-8d71254abdd2.png">

**Comment by beyhan** [comment] 2023-01-09 09:01
Hi @mmdacheva,

do you refer the docs about Unit [Testing with bosh-templates](https://bosh.io/docs/job-templates/)?

**Comment by mmdacheva** [comment] 2023-01-09 11:29
Yes, exactly, the information for which is in https://github.com/cloudfoundry/docs-bosh/blob/master/content/job-templates.md

**Comment by beyhan** [comment] 2023-01-09 13:12
BOSH doesn't support Ruby 3.2 yet and it will be added with https://github.com/cloudfoundry/bosh/pull/2418 and it looks like this will fix also the issue. Please check https://github.com/cloudfoundry/bosh/pull/2418/files#diff-a2f17697ae012217c3e84a9bb833714c0c290d6af45fffba3443a80a341718f1L63 and close this if it is the case.

**Comment by mmdacheva** [comment] 2023-01-10 12:31
Thank you for the provided information. I think this will resolve the issue we are experiencing

**Closed** 2023-01-10 12:31 UTC
